

spring:
  application:
    name: StudentsWebService
  # ==============================================================
  # = DBMS PostgreSQL Parameters
  # ==============================================================
  datasource:
    initialization-mode: always
    password: '01234'
    platform: postgres
    url: jdbc:postgresql://localhost:5433/University
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

logging:
  file:
    name: './logs/StudentsWebService.log'
    max-size: 1MB
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n%n"
    #console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    
  # Log General Level
  level:
   root: WARN
  # Log specific levels
   '[org.springframework.security]': DEBUG
   '[org.hibernate]': INFO
   '[org.springframework.web]': INFO   
   '[com.develop.webapp.controller]': INFO
  
# ==============================================================
# = Custom Parameters
# = Parameters to acces through UserCredentials Service
# ==============================================================
usercredential:
  serviceURL: http://localhost:8019/api/users/fetch/user/
  serviceURL2: http://localhost:8019/api/users/fetch/users
  userId: felice
  password: 
  
  
  
  
  
# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health, info, metrics, customStudentsInfo
   
   
# ==============================================================
# = Actuator Info
# ==============================================================
info:
  contact:
    name: "ferr"
    mail: "ferr@doiminio.it"
    phone: "3333333333"
    office-hours: "9-14"
  application:
    name-application: "Students Service - Basic Auth Version"
   
   
   
   