

spring:
  application:
    name: StudentsWebService
  # ==============================================================
  # = DBMS PostgreSQL Parameters
  # ==============================================================
  datasource:
    initialization-mode: always
    password: '01234'
    platform: postgres
    url: jdbc:postgresql://localhost:5433/University
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

