server:
  port: 8019

# ==============================================================
# = Users Credential Services
# ==============================================================
spring:
  application:
    name: UsersService
  # ==============================================================
  # = DBMS PostgreSQL Parameters
  # ==============================================================
  datasource:
    initialization-mode: always
    password: '01234'
    platform: postgres
    url: jdbc:postgresql://localhost:5434/UsersCredentials
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true


# ==============================================================
# = Log Properties Levels 
# = Default ERROR, WARN and INFO 
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ============================================================== 

logging:
  file:
    name: './logs/UsersCredentialsService.log'
    max-size: 1MB
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n%n"
    #console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    
  # Log General Level
  level:
   root: WARN
  # Log specific levels
   org.springframework.security: DEBUG
   org.hibernate: INFO
   org.springframework.web: INFO
   com.develop.credentials.controller: INFO

      
      


  